# BMP HEADER
.eqv	BMP_HEADER_MARKER		0
.eqv	BMP_HEADER_FILE_SIZE		2
.eqv	BMP_HEADER_RESERVED		6
.eqv	BMP_HEADER_OFFSET		10

# DIB HEADER
.eqv	BMP_HEADER_HEADER_SIZE		14
.eqv	BMP_HEADER_WIDTH		18
.eqv	BMP_HEADER_HEIGHT		22
.eqv	BMP_HEADER_PLANES		26
.eqv	BMP_HEADER_BITS_PER_PIXEL	28
.eqv	BMP_HEADER_COMPRESSION		30
.eqv	BMP_HEADER_IMAGE_SIZE		34
.eqv	BMP_HEADER_X_PER_METER		38
.eqv	BMP_HEADER_Y_PER_METER		42
.eqv	BMP_HEADER_COLORS		46
.eqv	BMP_HEADER_IMPORTANT_COLORS	50

# TYPICAL VALUES
.eqv	BMP_HEADER_T_SIZE		54
