# Image
.eqv	IMAGE_MAX_SIZE			230400

# ImageStruct
.eqv	IMAGE_STRUCT_FILENAME		0
.eqv	IMAGE_STRUCT_HEADER_DATA	4
.eqv	IMAGE_STRUCT_IMAGE_DATA		8
.eqv	IMAGE_STRUCT_WIDTH		12
.eqv	IMAGE_STRUCT_HEIGHT		16
.eqv	IMAGE_STRUCT_LINEBYTES		20

# ArgStruct
.eqv	ARG_STRUCT_X1			0
.eqv	ARG_STRUCT_Y1			4
.eqv	ARG_STRUCT_X2			8
.eqv	ARG_STRUCT_Y2			12
.eqv	ARG_STRUCT_THRESHOLD		16